services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./packages/api:/usr/src/app/packages/api
      - /usr/src/app/packages/api/node_modules
    command: pnpm --filter api run start:dev

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://api:3000
    depends_on:
      - api
    volumes:
      - ./packages/web:/usr/src/app/packages/web
      - /usr/src/app/packages/web/node_modules

volumes:
  postgres_data:

